In [1]:
import numpy as np  
arr=np.array([1,2,3,4,5])     # convert list into an array
print(arr)

[1 2 3 4 5]


In [3]:
print(np.sum(arr))    # find sum of an array

15


In [4]:
print(np.mean(arr))    # find mean of an array

3.0


In [5]:
print(arr**2)     # find squares of an array

[ 1  4  9 16 25]


In [23]:
print(np.zeros(5))        

[0. 0. 0. 0. 0.]


In [10]:
print(np.ones(10))    

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
print(np.zeros((5,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
print(np.arange(5,10))   # write numbers in an range

[5 6 7 8 9]


In [13]:
print(np.arange(1,10,2))  # write numbers in range with step

[1 3 5 7 9]


In [14]:
print(np.linspace(0,10,3))    # Evenly spaced numbers

[ 0.  5. 10.]


In [20]:
array=np.array([1,2,3,4,5,10])
print(array.max())   # Find Maximum Value
print(array.min())    # Finf Minimum Value

10
1


In [26]:
array=np.array([1,2,3,4,5,10])
a=array.reshape(3,2)    # change shape by dividing it.
print(a)

[[ 1  2]
 [ 3  4]
 [ 5 10]]


In [31]:
arr=np.array([2,5,6,1,8,3,2,10,9])
list=[4,5,6]
print(np.sort([4,6,8,1,3]))  # Sort Values 

[1 3 4 6 8]


In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))  # Concatenate two arrays
print(c)

[1 2 3 4 5 6]


In [36]:
arr=np.array([2,2,1,1,8,3,8,10,9])
print(np.unique(arr))  # Find Unique Values

[ 1  2  3  8  9 10]


In [41]:
t=np.array([[1,2,3],[4,5,6]])
print(np.transpose(t))  # Convet rows into columns

[[1 4]
 [2 5]
 [3 6]]


In [10]:
import numpy as np  
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=np.dot(a,b.T)  # Dot Produt
print(c)

[[14 32]
 [32 77]]


In [13]:
import numpy as np  
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.dot(a,b)  # Dot Produt
print(c)

32


In [5]:
z=np.array([1,2,3,4,5,6,7,8])
print(np.std(z))     # Find Standard Deviation

2.29128784747792


In [5]:
import numpy as np
print(np.eye(4,3))   # Return n*n matrix and diagonal value 1 and others zeros

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [9]:
print(np.full((3,4),2))   # Make matrix and return Specific Value in matrixnp.clip

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [10]:
arr=np.array([1,2,3,5,6,10,12,14,15,18,19])
print(np.clip(arr,3,15))    # write values in range 

[ 3  3  3  5  6 10 12 14 15 15 15]


In [11]:
arr=np.array([10,20,30,40])
print(np.where(arr>10))  # retyrn index based on condition

(array([1, 2, 3]),)


In [13]:
print(np.where(arr>20,arr,0))

[ 0  0 30 40]


In [14]:
marks=np.array([50,60,70,90,100,30,40,20,10,110])
print(np.where(marks>=50,"Pass","Fail"))

['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass']


In [16]:
arr=np.array([[5,4,6,1],[7,8,1,6]])
print(np.where(arr<5,-1,arr))

[[ 5 -1  6 -1]
 [ 7  8 -1  6]]


In [18]:
arr=np.array([-4,-3,3,4,-5])
print(np.where(arr<0,-arr,arr))  # Convert Negative Values to Positive

[4 3 3 4 5]


In [19]:
a=np.array([10,15,20])
b=np.array([5,20,25])
max=np.where(a>b,a,b)   # Return Maximum values
print(max)

[10 20 25]


In [20]:
arr=np.array([1,2,7,3,5])
print(np.argmax(arr))  # Find index of maximum Value

2


In [21]:
arr=np.array([1,2,7,3,5])
print(np.argmin(arr))  # Find index of minimum Value

0


In [22]:
arr=np.array([1,2,7,3,5])
print(np.cumsum(arr))  # find Commulative Sum

[ 1  3 10 13 18]


In [24]:
arr=np.array([1,2,3])
print(np.prod(arr))   # Find Product of all Values

6


In [25]:
arr=np.array([3.141,12.13455,3.4567])
print(np.round(arr,2))  # Round values

[ 3.14 12.13  3.46]


In [30]:
print(np.random.rand(5))   # Generate Random Numbers

[0.59366108 0.41505219 0.16921992 0.87064682 0.57660761]


In [31]:
print(np.identity(3))  # make Square Identity Matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
arr=np.array([10,1,2,3,4,7,8])
print(np.ptp(arr))   # find difference of maximum and minimum value.

9


In [34]:
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([10,1,2,3,4,7,8])
print(np.array_equal(a,b)) # Check if array equal retun true other false
print(np.array_equal(a,c))





True
False


In [36]:
# any check non zero num in arr if exit retrn true
a=np.array([0,0,0])
print(np.any(a))

False


In [38]:
print(np.tile([1,2,3],3))  # Incerese the size of an array by repeating exisying values

[1 2 3 1 2 3 1 2 3]


In [40]:
# tril return lower triangular part of an matrix
arr=np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(np.tril(arr))

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)



[[1 2 3]
 [4 5 6]]


In [18]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr1)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr4=np.array([1,2,3])
combined=np.vstack((arr1,arr2))
combined1=np.vstack((arr3,arr4))
print(combined)
print(combined1)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 2 3]]


In [27]:
pr

(2, 3)
(2, 3)


In [25]:
combined3=np.stack((combined,combined1))
print(combined3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [26]:
print(combined3.shape)

(2, 2, 3)


In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9])

a=arr.reshape(3,3)


print(a)
b=a.reshape(3,1,3)
print(b.flatten())




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,1,3))

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [39]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [43]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [44]:
print(arr.flatten())

[1 2 3 4 5 6 1 2 3 4 5 6]
